runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: https://github.com/faizal108/CC_GAE/tree/main/www/index.html
  upload: https://github.com/faizal108/CC_GAE/tree/main/www/index.html

- url: /(.*)
  static_files: https://github.com/faizal108/CC_GAE/tree/main/www/\1
  upload: https://github.com/faizal108/CC_GAE/tree/main/www/(.*)
